# Generated by Django 5.0.7 on 2024-09-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_username_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
