# Generated by Django 5.0.6 on 2024-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Fruta', 'Fruta'), ('Legume', 'Legume'), ('Verdura', 'Verdura')], default='Fruta', max_length=10),
        ),
    ]
