# Generated by Django 5.1 on 2024-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_notificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='data_envio',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='aceita',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(default='Mensagem padrão'),
        ),
    ]
